on: push
name: Update
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm update checker
      uses: MeilCli/npm-update-check-action@v3
    # - name: set remote url
    #   run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    # - name: package-update
    #   uses: ./.github/actions/actions-package-update
    #   env:
    #     AUTHOR_EMAIL: john@example.com
    #     AUTHOR_NAME: john
    #     EXECUTE: "true"
    #     GITHUB_TOKEN: ${{ secrets.SUPER_SECRET }}
    #     LOG_LEVEL: debug
    #   with:
    #     args: -u --packageFile package.json --loglevel verbose
